### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create container for the game
- [x] create div to hold the car
- [x] find and input a top down image of a car into the div
