### ISSUE TITLE
User can turn car

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create main.js file
- [x] create CSS classes for each of the 4 arrow keys
- [x] create an event listener for the arrow keys
- [x] in the event listener let each arrow key stroke assign their respective class to the car
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
