### ISSUE TITLE
Issue 3 User can start car

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] listen for the space bar key stroke
- [x] make the car image position absolute
- [x] every 16ms after the spacebar is pressed, increment the x-axis of position relative by a few pixels
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
