### ISSUE TITLE
Issue 4 User can stop car

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] add a boolean to the data model to indicate whether or not the car is started
- [x] add a conditional to the space bar event listener to refer to the boolean
- [x] in condition where car is started, stop the car by clearing the interval
