### ISSUE TITLE
issue 5 user can steer car

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/driving-game#9]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add a variable to the data model to see which direction the car is facing
- [x] add conditionals within the function to move the car to read the direction
- [x] each conditional will have the car move in the positive/negative x/y axis accordingly
